name: Python Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
    tags:
      - 'v*'


jobs:
  lints_pipeline:
    name: Lints CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [
          '3.10',
          '3.11',
        ]
    env:
      ENV: CI
      PYTHON: python
      QUICK_SERVER_DEBUG: 1
      RUN_ATEXIT: 1

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
        cache-dependency-path: |
          Makefile
          MANIFEST.in
          setup.cfg
          pyproject.toml

    - name: Install dependencies
      run: |
        PYTHON=${{ env.PYTHON }} make install

    - name: Lint Code (type-check)
      run: |
        PYTHON=${{ env.PYTHON }} make lint-type-check

    - name: Tests
      run: |
        PYTHON=${{ env.PYTHON }} make run-test

    - name: Lint Code (pylint)
      run: |
        PYTHON=${{ env.PYTHON }} make lint-pylint
